

; validates the stability of KVM in the linux kernel 
SUPOORTED_KVM_API_VERSION = 12
; Options include x86, S390, MIPS and arm  
VM_TYPE = ""
; Verified through the MSR_INDEX_LIST 
NUMBER_OF_GUESTS = 1
;GET MSR Feature index list
; Verifies the supportedfeatures by KVM 
GET_MSR_FEATURE_INDEX_LIST = 1